version: "3"

services:
  # Webサーバの設定
  web:
    container_name: web
    build:
      context: ./containers/apache
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "./containers/apache/user-vhosts:/etc/apache2/conf.d/vhosts:rw"
      - "./containers/apache/vhosts-manager:/var/www/vhostmanager:rw"
      - "./user-apps:/var/www/user-apps:rw"
    networks:
      uns_net:
        ipv4_address: 190.0.0.10

  # メールサーバの設定
  mail:
    container_name: mail
    image: kanemu/maildev-with-iconv
    ports:
      - "1025:25"
      - "8025:80"
    networks:
      uns_net:
        ipv4_address: 190.0.0.11

  # wordpress用データベースサーバの設定
  db:
    container_name: db
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysqladmin
    networks:
      uns_net:
        ipv4_address: 190.0.0.12

  # dbのGUI設定
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      uns_net:
        ipv4_address: 190.0.0.20

volumes:
    db_data:

networks:
  uns_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 190.0.0.0/24
